### PR TITLE
docs: add deno example

### PR DESCRIPTION
**Pull request by johnhooks**
I've been playing with using Dinero.js with Deno. It requires using an import map. I thought an example might be helpful.

I will need to figure out how to change the version numbers in the `import_map.json`. I also don't know if for the example the `deno.lock` file should be committed.

The example has the exact same contents as `example/starter`.

### CODE REVIEW

**Comment by sarahdayan** [comment]
Neat! I've pushed some slight changes to use npm specifiers, this way there's no need for import maps.

**Comment by johnhooks** [comment]
@sarahdayan I forgot about the npm specifier, thanks! That is cleaner.

**Comment by johnhooks** [comment]
Can codesandbox run Deno modules?

**Comment by sarahdayan** [comment]
@johnhooks Not natively. We need to use a `package.json` file and install Deno (see example [here](https://codesandbox.io/s/y56n2?file=/package.json)).

I think it's fine not to do it.

**Comment by sarahdayan** [comment]
One thing to figure out before moving on though is how to make this example play ball with Ship.js and Lerna.

When releasing a new version with Ship.js, once the new version is selected, Lerna runs to update the version of the library everywhere including in the examples (in the `package.json`). Then, Ship.js runs `yarn install` which updates `yarn.lock`, etc.

This won't work out of the box with the Deno example, as I don't think it supports Deno at all.

Maybe one lead is to use relative dependencies instead of npm specifiers?

**Comment by johnhooks** [comment]
That works if someone downloads the whole repo, but it is confusing if a beginner uses the example as an "example" and copy and pastes.

Maybe relative imports, details in the README.md, a docs page about importing in Deno, and a preemptive GitHub issue or discussion could help solve possible confusion.

**Comment by sarahdayan** [comment]
@johnhooks I hoped we could use range versions (`@2`) but it doesn't appear to be working… maybe because the packages are still alpha?

Another route would be to update [this script](https://github.com/dinerojs/dinero.js/blob/main/ship.config.js#L18-L27) to update the versions in the example and re-compile the lock file.

**Comment by johnhooks** [comment]
But the lockfile won't update until the packages are published because the aren't available... right?

**Comment by johnhooks** [comment]
I tried the range version with `npm:date-fns@2` and it worked. So it probably will work when `dinero.js` is out of alpha. Though it does add a specific version to the lock file. So it doesn't really fix anything. But it is a rather small issue, especially with such a simple example. 

I like the changes you made.

**Comment by johnhooks** [comment]
What I was referring to was the lock file specifically. Unless you want to manually edit it, it can't be updated until after the packages are released. It can probably be cleaned up with a script, but ship.js doesn't have a `packagesPublished` hook. It looks like there is a hook for Slack, but not a regular hook.

**Comment by sarahdayan** [comment]
I forgot that there's sub-resource integrity here 🤦 

Another solution is to remove the lock file and exclude it from version control. Users can build it locally. It's only an example, this isn't that big of a deal.

**Comment by johnhooks** [comment]
> Another solution is to remove the lock file and exclude it from version control

I think that is simplest

**Comment by johnhooks** [comment]
@sarahdayan I removed the lock file and rebase to main. It should be ready.

**Comment by sarahdayan** [comment]
@johnhooks Yes let's ignore this example for now. I couldn't find anything related to it in the Deno docs, and I believe npm specifiers are still [quite experimental](https://github.com/denoland/deno/issues/15960) so let's move forward.

**Comment by johnhooks** [comment]
@sarahdayan It should be good now.

**Review by sarahdayan — APPROVED** [review]
Go Deno 🚀

**Pull request merged**
