### PR TITLE
docs: Delete redundant characters.

### PR DESCRIPTION
**Pull request by luc4leone**
Delete in an HTML anchor tag these characters "(",  "\&gt;)" because they resulted in a typo.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Compliance

- [x] My change isn't breaking (it doesn't cause existing functionality to change).
- [x] I have read the [CONTRIBUTING](https://github.com/sarahdayan/dinero.js/blob/develop/CONTRIBUTING.md) document.
- [ ] My code follows the coding style of this project.
- [x] I have properly formatted my commit messages with [cz-cli](https://github.com/commitizen/cz-cli), or manually, following the [Angular Commit Messages Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] I have updated the documentation accordingly, or my changes doesn't require documentation changes.
- [ ] I have added tests to cover my changes, or my changes doesn't require new tests.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by luc4leone** [comment]
Sorry @sarahdayan, I read the contributing guidelines, but clearly not as carefully as I should have. I didn't get the point that the docs are generated from the code. Since I didn't know JSDoc, I read its documentation to understand. After some experimenting I think I identified the right place: it's in the `README.md`.

I deleted the 2 parenthesis in the url and after executing in my terminal `npm run docs`, I checked the `docs/index.html` in the editor and also the rendering in the browser, and everything seems right now.

**Comment by luc4leone** [comment]
I deleted the first incorrect commit @sarahdayan

**Comment by sarahdayan** [comment]
Hi @luc4leone, there are still things to fix:

1. You need to target the `develop` branch.
2. You're currently using the link `https://en.wikipedia.org/wiki/ISO_4217#Treatment_of_minor_currency_units_the_%22exponent%22`, which doesn't work (if you try it in your browser directly, it won't jump to the right section). You need to use `https://en.wikipedia.org/wiki/ISO_4217#Treatment_of_minor_currency_units_.28the_.22exponent.22.29`.

Once both are fixed, I'll merge your PR.

**Comment by luc4leone** [comment]
> Hi @luc4leone, there are still things to fix:

I'll take care of them this week, thanks @sarahdayan!

**Comment by sarahdayan** [comment]
@luc4leone Any new on this? 🙂

**Comment by luc4leone** [comment]
Hey @sarahdayan ;-) 

will take of it tomorrow.

**Comment by luc4leone** [comment]
Actually I didn't want to open a new PR @sarahdayan, see #124, but I guess that by targeting `develop` that's what happened. Was there a way to update this one anyway? (so that next time something similar happen again, I'll be able to do it). Thanks :)

**Comment by sarahdayan** [comment]
We can continue on #124 :) Closing this one.

**Pull request closed without merging**
